INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('American Business','Ray Springsteen','C (270) 319-2488');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('American Cultures','Calla Banks','C (270) 765-2507');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('American Heritage','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('American Heritage','Calla Banks','C (270) 765-2507');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('American Labor','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Animal Science','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Animation','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Archaeology','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Archery','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Architecture','Chris Hutchens','C (270) 312-3443');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Art','Amanda Hall','C (270) 300-4064');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Astronomy','Amanda Hall','C (270) 300-4064');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Athletics','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Automotive Maintenance','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Aviation','Jim Sedlak','C (703) 216-8097');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Aviation','Carl Swope','C (270) 307-8687');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Backpacking','Casey Geist','C (910) 273-7382');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Backpacking','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Basketry','Amanda Hall','C (270) 300-4064');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Bird Study','Amanda Hall','C (270) 300-4064');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Bugling','Ron Waldorf','C (270) 872-8559');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Camping (Eagle)','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Camping (Eagle)','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Camping (Eagle)','Casey Geist','C (910) 273-7382');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Canoeing','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Chemistry','Ron Waldorf','C (270) 872-8559');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Chess','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Citizenship In Society (Eagle)','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Citizenship In Community (Eagle)','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Citizenship In The Nation (Eagle)','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Citizenship In The World (Eagle)','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Climbing','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Coin Collection','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Collections','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Communications','David Bashaw','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Communications','Jim Sedlak','C(703) 216-8097');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Composite Materials','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Cooking (Eagle)','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Cooking (Eagle)','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Crime Prevention','David Bashaw','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Cycling (Eagle)','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Cycling (Eagle)','Ray Springsteen','C (270) 319-2488');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Dentistry','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Digital Technology','Matt Carrier','C (502) 428-9097');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Disabilities Awareness','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Dog Care','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Dog Care','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Drafting','Chris Hutchens','C (270) 312-3443');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Electricity','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Electronics','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Emergency Preparedness (Eagle)','Casey Geist','C (910) 273-7382');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Emergency Preparedness (Eagle)','Jim Sedlak','C (703) 216-8097');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Energy','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Engineering','Chris Hutchens','C (270) 312-3443');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Entrepreneurship','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Environmental Science (Eagle)','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Exploration','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Family Life (Eagle)','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Family Life (Eagle)','Jim Sedlak','C (703) 216-8097');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Farm Mechanics','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Fingerprinting','Ron Waldorf','C (270) 872-8559');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Fire Safety','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('First Aid (Eagle)','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('First Aid (Eagle)','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Fish And Wildlife Management','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Fishing','Ron Waldorf','C (270) 872-8559');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Fishing','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Fly Fishing','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Fly Fishing','David Bashaw','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Forestry','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Game Design','Matt Carrier','C (502) 428-9097');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Gardening','Betty Kim','C (270) 300-6575');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Genealogy','Amanda Hall','C (270) 300-4064');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Geocaching','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Geocaching','Casey Geist','C (910) 273-7382');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Geology','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Golf','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Graphic Arts','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Hiking (Eagle)','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Hiking (Eagle)','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Hiking (Eagle)','Casey Geist','C (910) 273-7382');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Home Repairs','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Horsemanship','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Indian Lore','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Insect Study','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Inventing','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Journalism','Ray Springsteen','C (270) 319-2488');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Kayaking','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Landscape Architecture','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Law','David Bashaw','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Leatherworking','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Lifesaving (Eagle)','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Mammal Study','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Medicine','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Metalwork','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Mining In Society','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Model Design And Building','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Motorboating','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Moviemaking','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Music','Betty Kim','C (270) 300-6575');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Nature','Betty Kim','C (270) 300-6575');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Nuclear Science','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Oceanography','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Orienteering','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Orienteering','Casey Geist','C (910) 273-7382');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Painting','Amanda Hall','C (270) 300-4064');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Personal Fitness (Eagle)','Chris Worrill','C (270) 317-0038');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Personal Fitness (Eagle)','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Personal Fitness (Eagle)','Ray Springsteen','C (270) 319-2488');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Personal Management (Eagle)','Ray Springsteen','C (270) 319-2488');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Pets','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Photography','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Photography','Ron Waldorf','C (270) 872-8559');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Plant Science','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Plumbing','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Pottery','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Programming','Matt Carrier','C (502) 428-9097');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Public Health','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Public Speaking','David Bashaw','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Pulp And Paper','Amanda Hall','C (270) 300-4064');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Radio','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Railroading','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Reading','Betty Kim','C (270) 300-6575');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Reading','Amanda Hall','C (270) 300-4064');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Reptile And Amphibian Study','Betty Kim','C (270) 300-6575');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Rifle Shooting','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Robotics','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Rowing','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Safety','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Salesmanship','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Scouting Heritage','Calla Banks','C (270) 765-2507');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Scholarship','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Scholarship','Betty Kim','C (270) 300-6575');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Scuba Diving','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Sculpture','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Search And Rescue','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Shotgun Shooting','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Signs, Signals, And Codes','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Skating','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Small-Boat Sailing','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Snow Sports','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Soil And Water Conservation','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Space Exploration','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Sports','Amber Hutchens','C (270) 317-0025');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Stamp Collecting','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Surveying','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Sustainability (Eagle)','Betty Kim','C (270) 300-6575');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Swimming (Eagle)','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Textile','Amanda Hall','C (270) 300-4064');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Theater','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Traffic Safety','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Truck Transportation','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Veterinary Medicine','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Water Sports','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Weather','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Welding','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Whitewater','','');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Wilderness Survival','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Wood Carving','Jonathan Hall Sr','C (931) 241-9207');
INSERT INTO BSATroop829_db.dbo.MeritBadgeCounselors (MeritBadgeName,CounselorName,CounselorPhoneNumber) VALUES ('Woodworking','Jonathan Hall Sr','C (931) 241-9207');
